"""Pluggable LLM providers.

- StubProvider: deterministic, dependency-free. Produces a grounded explanation
  from the evidence without any external service. Always available.
- GroqProvider: uses the `groq` SDK (free tier). Requires GROQ_API_KEY.
- BedrockProvider: uses `boto3` against Amazon Bedrock.

If a configured provider fails to initialize or errors at call time, callers
fall back to the stub so security enforcement never depends on the LLM.
"""

from __future__ import annotations

from batman.config import Settings, get_settings


class LLMProvider:
    name = "base"

    def generate(self, prompt: str, system: str = "") -> str:
        raise NotImplementedError

    @property
    def available(self) -> bool:
        return True


class StubProvider(LLMProvider):
    """Deterministic explanation generator. No external dependencies."""

    name = "stub"

    def generate(self, prompt: str, system: str = "") -> str:
        # Return a minimal JSON object. The investigation agent has a robust
        # fallback that builds a full explanation from evidence, so this only
        # needs to be valid and non-misleading.
        return (
            '{"summary": "Stub explanation generated without an LLM. '
            'See detector evidence for details.", '
            '"threat_type": "UNKNOWN", "evidence": [], '
            '"uncertainty": "Generated by deterministic stub; no model reasoning applied.", '
            '"recommended_action": "ESCALATE"}'
        )


class GroqProvider(LLMProvider):
    name = "groq"

    def __init__(self, settings: Settings):
        self._client = None
        self._model = settings.groq_model
        self._settings = settings
        try:
            from groq import Groq  # type: ignore

            if settings.groq_api_key:
                self._client = Groq(api_key=settings.groq_api_key)
        except Exception:
            self._client = None

    @property
    def available(self) -> bool:
        return self._client is not None

    def generate(self, prompt: str, system: str = "") -> str:
        if not self._client:
            raise RuntimeError("groq_unavailable")
        resp = self._client.chat.completions.create(
            model=self._model,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": prompt},
            ],
            temperature=0.2,
            max_tokens=700,
        )
        return resp.choices[0].message.content or ""


class BedrockProvider(LLMProvider):
    name = "bedrock"

    def __init__(self, settings: Settings):
        self._client = None
        self._model_id = settings.bedrock_model_id
        try:
            import boto3  # type: ignore

            self._client = boto3.client("bedrock-runtime", region_name=settings.aws_region)
        except Exception:
            self._client = None

    @property
    def available(self) -> bool:
        return self._client is not None

    def generate(self, prompt: str, system: str = "") -> str:
        if not self._client:
            raise RuntimeError("bedrock_unavailable")
        import json

        body = {
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": 700,
            "temperature": 0.2,
            "system": system,
            "messages": [{"role": "user", "content": prompt}],
        }
        resp = self._client.invoke_model(
            modelId=self._model_id, body=json.dumps(body)
        )
        payload = json.loads(resp["body"].read())
        # Claude on Bedrock returns content as a list of blocks.
        parts = payload.get("content", [])
        if isinstance(parts, list):
            return "".join(p.get("text", "") for p in parts)
        return str(payload)


def get_llm_provider(settings: Settings | None = None) -> LLMProvider:
    settings = settings or get_settings()
    choice = (settings.llm_provider or "stub").lower()
    provider: LLMProvider
    if choice == "groq":
        provider = GroqProvider(settings)
    elif choice == "bedrock":
        provider = BedrockProvider(settings)
    else:
        return StubProvider()

    # Fall back to stub if the configured provider could not initialize.
    if not provider.available:
        return StubProvider()
    return provider
